services:
  airflow:
    image: apache/airflow:2.10.1-python3.10
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../warehouse:/opt/airflow/warehouse
      - ../data:/opt/airflow/data
    ports:
      - "8888:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --role Admin --firstname Admin --lastname User --email admin@example.com &&
               airflow webserver & airflow scheduler"
